//User clicks an image and makes it go to the canvas
var bkg;
var img;
var x=10;
var dx=0.25;
var mountain;
var mountainx=960;
var mountaindx=1;
var carmodel;
var kmarker1;
var kmarker1x=700;
var kmarker1dx=8;
var kmarker2;
var kmarker2x=5600;
var kmarker2dx=8;
var kmarker3;
var kmarker3x=8800;
var kmarker3dx=8;
var kmarker4;
var kmarker4x=15100;
var kmarker4dx=8;
var kmarker5;
var kmarker5x=19300;
var kmarker5dx=8;
var kmarker6;
var kmarker6x=20700;
var kmarker6dx=8;
var kmarker7;
var kmarker7x=24000;
var kmarker7dx=8;
var finflag;
var finflagx=26800;
var finflagdx=8;
var tree1;
var tree1x=700;
var tree3x=4500;
var tree5x=8600;
var tree7x=13000;
var tree9x=18000;
var tree11x=21000;
var tree13x=26000;
var tree1dx=8;
var tree2;
var tree2x=1200;
var tree4x=5700;
var tree6x=11200;
var tree8x=16000;
var tree10x=19400;
var tree12x=23900;
var tree14x=25050;
var tree2dx=12;
var score=0;
var gametag=prompt("If you are playing this game as a class, enter the gametag given to you: ");
var playername=prompt("Enter your name (first names will suffice, we are among friends here): ");


function chooseCar(carmodel){
  img=new Image();
  img.src="images/"+carmodel+".png";
  bkg=new Image();
  bkg.src="images/landscape.png";
  mountain=new Image();
  mountain.src="images/mountain.png";
  tree1=new Image();
  tree1.src="images/tree1.png";
  var tree3=tree1;
  tree2=new Image();
  tree2.src="images/tree2.png";
  kmarker1=new Image();
  kmarker1.src="images/kmarker1.png";
  kmarker2=new Image();
  kmarker2.src="images/kmarker2.png";
  kmarker3=new Image();
  kmarker3.src="images/kmarker3.png";
  kmarker4=new Image();
  kmarker4.src="images/kmarker4.png";
  kmarker5=new Image();
  kmarker5.src="images/kmarker5.png";
  kmarker6=new Image();
  kmarker6.src="images/kmarker6.png";
  kmarker7=new Image();
  kmarker7.src="images/kmarker7.png";
  finflag=new Image();
  finflag.src="images/finflag.png";
  var startbutton=document.getElementById("startbutton");
  startbutton.style.display="inline-block";
  document.getElementById("car").value="images/"+carmodel+".png";
  document.getElementById("startbutton").style.color="black";
  return img, carmodel;
}

//displays questions
function placeCar(){
  document.getElementById("questions").style.display="block";
  document.getElementById("questionbody").innerHTML="Place your car on the racetrack!";
  document.getElementById("option1").value=25;
  document.getElementById("option1").innerHTML="Place car!";
  document.getElementById("question").onchange=function(){
  score=score+parseInt(document.getElementById("question").value);
  moveCar();
  displayQuestions();
  scrollDown();
};

function displayQuestions(){
    document.getElementById("questions").style.display="block";
    document.getElementById("questionbody").innerHTML="What topic are you going to choose?";
    document.getElementById("option0").selected="selected";
    document.getElementById("option1").value=50;
    document.getElementById("option1").innerHTML="The professor/instructor will choose the topics for us.";
    document.getElementById("option2").value=49;
    document.getElementById("option2").innerHTML="The professor/instructor will have us choose from a number of relevant topics.";
    document.getElementById("option3").value=48;
    document.getElementById("option3").innerHTML="I don’t know yet, but whatever I choose, it better be something I find interesting or I am curious about. Doing research on a boring topic makes me not want to do it at all.";
    document.getElementById("option4").value=47;
    document.getElementById("option4").innerHTML="I know what I want to research, but I am not sure if I can find information about my topic.";
    document.getElementById("question").onchange=function(){
      score=score+parseInt(document.getElementById("question").value);
      moveCar();
      sendToDb();
      document.getElementById("questionbody").innerHTML="After you have chosen your topic, how do you know if there is enough information about it?";
      document.getElementById("option0").selected="selected";
      document.getElementById("option1").value=48;
      document.getElementById("option1").innerHTML="I have some ideas, but I will talk with my instructor or a librarian to see if my topic is a good one for this assignment.";
      document.getElementById("option2").value=50;
      document.getElementById("option2").innerHTML="I can talk to a librarian and set an appointment for a research consultation.";
      document.getElementById("option3").value=49;
      document.getElementById("option3").innerHTML="I can look up my topic in dictionaries and encyclopedias. I can get keywords from them, too.";
      document.getElementById("option4").value=47;
      document.getElementById("option4").innerHTML="I already know most of the relevant information about my topic. I will get the research done later. ";
      document.getElementById("question").onchange=function(){
        score=score+parseInt(document.getElementById("question").value);
        moveCar();
        sendToDb();
        document.getElementById("questionbody").innerHTML="How do you come up with the right keywords for your topic?";
        document.getElementById("option0").selected="selected";
        document.getElementById("option1").value=48;
        document.getElementById("option1").innerHTML="I can ask a librarian or my instructor where to go to find keywords.";
        document.getElementById("option2").value=50;
        document.getElementById("option2").innerHTML="I will state my topic as a research question and extract keywords from there.";
        document.getElementById("option3").value=49;
        document.getElementById("option3").innerHTML="I will look up keywords in encyclopedias and dictionaries.";
        document.getElementById("option4").value=47;
        document.getElementById("option4").innerHTML="I don’t think keywords will be a problem.";
        document.getElementById("question").onchange=function(){
          score=score+parseInt(document.getElementById("question").value);
          moveCar();
          sendToDb();
          document.getElementById("questionbody").innerHTML="Now that you have a topic and keywords, you need to get some background information about your topic, how will you do that?";
          document.getElementById("option0").selected="selected";
          document.getElementById("option1").value=48;
          document.getElementById("option1").innerHTML="I will read encyclopedia and dictionary entries about my topic. Those are good sources to find background information.";
          document.getElementById("option2").value=50;
          document.getElementById("option2").innerHTML="I will ask my professor/instructor or a librarian about where to find background information on my topic.";
          document.getElementById("option3").value=49;
          document.getElementById("option3").innerHTML="I am just going to wing it. I am sure I can find good information through my facebook and twitter feeds.";
          document.getElementById("option4").value=47;
          document.getElementById("option4").innerHTML="I am very familiar with the topic and have all the background information I need already.";
          document.getElementById("question").onchange=function(){
            score=score+parseInt(document.getElementById("question").value);
            moveCar();
            sendToDb();
            document.getElementById("questionbody").innerHTML="When you look for background information in encyclopedias, you will often find a list at the end of the entry. What is it and what can you do with it?";
            document.getElementById("option0").selected="selected";
            document.getElementById("option1").value=48;
            document.getElementById("option1").innerHTML="It’s a bibliography. It is a list of the sources the author used to write the entry. I can see where the author got their information and I can check those sources myself.";
            document.getElementById("option2").value=50;
            document.getElementById("option2").innerHTML="It’s a bibliography. It’s what the author used for their research. I have nothing to do with it.";
            document.getElementById("option3").value=49;
            document.getElementById("option3").innerHTML="It’s a list of sources used to write the entry. I can show it to a librarian and they can tell me how to get to those sources.";
            document.getElementById("option4").value=47;
            document.getElementById("option4").innerHTML="I don’t know. It looks like a list of sources, but I don’t know if I can even get to them if I wanted to.";
            document.getElementById("question").onchange=function(){
              score=score+parseInt(document.getElementById("question").value);
              moveCar();
              // sendToDb();
              document.getElementById("questionbody").innerHTML="Books play a specific role in your research, what is it?";
              document.getElementById("option0").selected="selected";
              document.getElementById("option1").value=48;
              document.getElementById("option1").innerHTML="Books provide good in-depth information about my topic.";
              document.getElementById("option2").value=50;
              document.getElementById("option2").innerHTML="Books are a very trustworthy source of information.";
              document.getElementById("option3").value=49;
              document.getElementById("option3").innerHTML="My instructor requires us to use only books for our research.";
              document.getElementById("option4").value=47;
              document.getElementById("option4").innerHTML="I actually don’t know why I have to use books when I can find anything I need on the Internet. ";
              document.getElementById("question").onchange=function(){
                score=score+parseInt(document.getElementById("question").value);
                moveCar();
                sendToDb();
                document.getElementById("questionbody").innerHTML="You have a topic, keywords and background information, now it’s time to find books and videos about my topic. How do you find the books you will need?";
                document.getElementById("option0").selected="selected";
                document.getElementById("option1").value=48;
                document.getElementById("option1").innerHTML="I can find books in my library by typing my keywords in the online library catalog. I can get a list of available books and media that way.";
                document.getElementById("option2").value=50;
                document.getElementById("option2").innerHTML="I will go to the reference desk and ask a librarian for help finding books and videos for my topic.";
                document.getElementById("option3").value=49;
                document.getElementById("option3").innerHTML="I have a couple of books on the topic at home. I bet those will be enough.";
                document.getElementById("option4").value=47;
                document.getElementById("option4").innerHTML="Books? I can find all that online, no need for books, no problem.";
                document.getElementById("question").onchange=function(){
                  score=score+parseInt(document.getElementById("question").value);
                  moveCar();
                  sendToDb();
                  document.getElementById("questionbody").innerHTML="<span>Let’s try finding a book in the library catalog. Open the <a href='https://www.worldcat.org' target='new'>OCLC Worldcat</a> catalog and type “brief history of time” in the search field. Among all the books, videos, etc., what did you find?</span>";
                  document.getElementById("option0").selected="selected";
                  document.getElementById("option1").value=48;
                  document.getElementById("option1").innerHTML="Option 5";
                  document.getElementById("option2").value=50;
                  document.getElementById("option2").innerHTML="Option 6";
                  document.getElementById("option3").value=49;
                  document.getElementById("option3").innerHTML="Option 7";
                  document.getElementById("option4").value=47;
                  document.getElementById("option4").innerHTML="Option 8";
                  document.getElementById("question").onchange=function(){
                    score=score+parseInt(document.getElementById("question").value);
                    moveCar();
                    sendToDb();
                    document.getElementById("questionbody").innerHTML="What can you do if you can’t find books and/or other sources about your topic?";
                    document.getElementById("option0").selected="selected";
                    document.getElementById("option1").value=48;
                    document.getElementById("option1").innerHTML="If I can’t find it, it probably doesn’t exist.";
                    document.getElementById("option2").value=50;
                    document.getElementById("option2").innerHTML="I can ask a librarian at the reference desk if the books I am looking for are available and how to get them.";
                    document.getElementById("option3").value=49;
                    document.getElementById("option3").innerHTML="I will just go online to see if I can find the information i need from the web.";
                    document.getElementById("option4").value=47;
                    document.getElementById("option4").innerHTML="Maybe my topic is too new, too obscure, or there’s just not enough information about my topic.";
                    document.getElementById("question").onchange=function(){
                      score=score+parseInt(document.getElementById("question").value);
                      moveCar();
                      sendToDb();
                      document.getElementById("questionbody").innerHTML="What role do scholarly articles from databases play in your research?";
                      document.getElementById("option0").selected="selected";
                      document.getElementById("option1").value=48;
                      document.getElementById("option1").innerHTML="Scholarly articles would provide the latest information coming from universities, colleges and research institutions about my topic.";
                      document.getElementById("option2").value=50;
                      document.getElementById("option2").innerHTML="Articles are good because they come from colleges and universities.";
                      document.getElementById("option3").value=49;
                      document.getElementById("option3").innerHTML="Peer-reviewed articles contain basic information about my topic.";
                      document.getElementById("option4").value=47;
                      document.getElementById("option4").innerHTML="Scholarly articles are written in a very hard to understand language. Makes my paper look good just by including them in my research.";
                      document.getElementById("question").onchange=function(){
                      score=score+parseInt(document.getElementById("question").value);
                      moveCar();
                      sendToDb();
                        document.getElementById("questionbody").innerHTML="What is peer review?";
                        document.getElementById("option0").selected="selected";
                        document.getElementById("option1").value=48;
                        document.getElementById("option1").innerHTML="Peer review is when an article written by a scholar or researcher is reviewed by his/her colleagues, typically other professionals knowledgeable on the subject.";
                        document.getElementById("option2").value=50;
                        document.getElementById("option2").innerHTML="Peer review is what all articles from academic journals have to go through to be considered academic journal articles.";
                        document.getElementById("option3").value=49;
                        document.getElementById("option3").innerHTML="Peer review is what all articles written by professors are called.";
                        document.getElementById("option4").value=47;
                        document.getElementById("option4").innerHTML="I don't know, but sounds important.";
                        document.getElementById("question").onchange=function(){
                        score=score+parseInt(document.getElementById("question").value);
                        moveCar();
                        sendToDb();
                          document.getElementById("questionbody").innerHTML="There is a very interesting articles about <strong>mosquitoes</strong> and <strong>cheese</strong> written by Bart <strong>Knols</strong>. Look up the article in WorldCat using the keywords above, the article is about:";
                          document.getElementById("option0").selected="selected";
                          document.getElementById("option1").value=48;
                          document.getElementById("option1").innerHTML="How mosquitoes are attracted Limburger cheese, presumably because it smells like feet and armpits.";
                          document.getElementById("option2").value=50;
                          document.getElementById("option2").innerHTML="How to prevent mosquito bites.";
                          document.getElementById("option3").value=49;
                          document.getElementById("option3").innerHTML="Explaining the relationship between mosquitoes and cheese.";
                          document.getElementById("option4").value=47;
                          document.getElementById("option4").innerHTML="Something about mosquitoes and cheese, but couldn’t tell exactly what.";
                          document.getElementById("question").onchange=function(){
                          score=score+parseInt(document.getElementById("question").value);
                          moveCar();
                          sendToDb();
                            document.getElementById("questionbody").innerHTML="Many students rely on the web to find basic information or journal articles about a topic, usually:";
                            document.getElementById("option0").selected="selected";
                            document.getElementById("option1").value=48;
                            document.getElementById("option1").innerHTML="It is easy to find encyclopedia entries through a basic google search and scholarly articles using Google Scholar. However, the encyclopedia articles would be likely from Wikipedia and scholarly articles are usually not available in full text because paywalls.";
                            document.getElementById("option2").value=50;
                            document.getElementById("option2").innerHTML="The best information on a topic is invariably found on the web.";
                            document.getElementById("option3").value=49;
                            document.getElementById("option3").innerHTML="Good information has to be separated from junk, advertisements, and opinions disguised as fact.";
                            document.getElementById("option4").value=47;
                            document.getElementById("option4").innerHTML="The Internet is a good source for obscure and/or new topics, for which there is not enough information.";
                            document.getElementById("question").onchange=function(){
                            score=score+parseInt(document.getElementById("question").value);
                            moveCar();
                            sendToDb();
                              document.getElementById("questionbody").innerHTML="What does it mean to <strong>evaluate</strong> the information you find?";
                              document.getElementById("option0").selected="selected";
                              document.getElementById("option1").value=48;
                              document.getElementById("option1").innerHTML="Making sure the information I find comes from a trustworthy source, its publication date satisfies my requirements, equally good sources were used to write the article, and the author has the right credentials or qualifications to write about the topic.";
                              document.getElementById("option2").value=50;
                              document.getElementById("option2").innerHTML="It means checking with my instructor to make sure my sources are good to include in my research.";
                              document.getElementById("option3").value=49;
                              document.getElementById("option3").innerHTML="If I read the articles out-loud, and if it sounds like a professor wrote it, it must be okay.";
                              document.getElementById("option4").value=47;
                              document.getElementById("option4").innerHTML="It means the information was vetted by a librarian when I requested it.";
                              document.getElementById("question").onchange=function(){
                              score=score+parseInt(document.getElementById("question").value);
                              moveCar();
                              sendToDb();
                                document.getElementById("questionbody").innerHTML="What would be four important factors to consider when evaluating sources?";
                                document.getElementById("option0").selected="selected";
                                document.getElementById("option1").value=48;
                                document.getElementById("option1").innerHTML="The date the article was published, the author’s credentials or qualifications, the sources the author used to write his/her own article, and the purpose of the article.";
                                document.getElementById("option2").value=50;
                                document.getElementById("option2").innerHTML="If the author has a Dr. or PhD, attached to his/her name.";
                                document.getElementById("option3").value=49;
                                document.getElementById("option3").innerHTML="If the article came from the library.";
                                document.getElementById("option4").value=47;
                                document.getElementById("option4").innerHTML="I have no problem taking any information I find at face value.";
                                document.getElementById("question").onchange=function(){
                                score=score+parseInt(document.getElementById("question").value);
                                moveCar();
                                sendToDb();
                                  document.getElementById("questionbody").innerHTML="What style are you using?";
                                  document.getElementById("option0").selected="selected";
                                  document.getElementById("option1").value=48;
                                  document.getElementById("option1").innerHTML="MLA";
                                  document.getElementById("option2").value=50;
                                  document.getElementById("option2").innerHTML="APA";
                                  document.getElementById("option3").value=49;
                                  document.getElementById("option3").innerHTML="Chicago/CSE";
                                  document.getElementById("option4").value=47;
                                  document.getElementById("option4").innerHTML="Other";
                                  document.getElementById("question").onchange=function(){
                                  score=score+parseInt(document.getElementById("question").value);
                                  moveCar();
                                  sendToDb();
                                    document.getElementById("questionbody").innerHTML="Why does your instructor/professor ask you to use a particular style?";
                                    document.getElementById("option0").selected="selected";
                                    document.getElementById("option1").value=48;
                                    document.getElementById("option1").innerHTML="When storing thousands of articles in one place, having them using the same structure and having them written using the same rules make them easier to find.";
                                    document.getElementById("option2").value=50;
                                    document.getElementById("option2").innerHTML="That’s just how they like stuff I turn in.";
                                    document.getElementById("option3").value=49;
                                    document.getElementById("option3").innerHTML="Having rules makes the job easier to do.";
                                    document.getElementById("option4").value=47;
                                    document.getElementById("option4").innerHTML="It’s just a funny academic quirk that has been around for ages and no one has ever thought about changing.";
                                    document.getElementById("question").onchange=function(){
                                    score=score+parseInt(document.getElementById("question").value);
                                    moveCar();
                                    sendToDb();
                                    document.getElementById("questions").style.display="none";
                                    startbutton.style.display="none";
                                    return;
                                    };
                                  };
                                };
                              };
                            };
                          };
                        };
                      };
                    };
                  };
                };
              };
            };
          };
        };
      };
    };
  };
}

function moveCar(){
  //moves car every time a question is answered
  var raceCanvas=document.getElementById("racecanvas");
  raceCanvas.height=720;
  raceCanvas.width=window.innerWidth;
  var ctx=raceCanvas.getContext("2d");
  ctx.drawImage(bkg, 0, 0);
  var cartoon=requestAnimationFrame(moveCar);
  ctx.drawImage(mountain, mountainx, 145);
  mountainx-=mountaindx;
  ctx.drawImage(tree1, tree1x, 100);
  tree1x-=tree1dx;
  ctx.drawImage(tree1, tree3x, 100);
  tree3x-=tree1dx;
  ctx.drawImage(tree1, tree5x, 100);
  tree5x-=tree1dx;
  ctx.drawImage(tree1, tree7x, 100);
  tree7x-=tree1dx;
  ctx.drawImage(tree1, tree9x, 100);
  tree9x-=tree1dx;
  ctx.drawImage(tree1, tree11x, 100);
  tree11x-=tree1dx;
  ctx.drawImage(tree1, tree13x, 100);
  tree13x-=tree1dx;
  ctx.drawImage(kmarker1, kmarker1x, 370, 450, 300);
  kmarker1x-=kmarker1dx;
  ctx.drawImage(kmarker2, kmarker2x, 370, 450, 300);
  kmarker2x-=kmarker2dx;
  ctx.drawImage(kmarker3, kmarker3x, 370, 450, 300);
  kmarker3x-=kmarker3dx;
  ctx.drawImage(kmarker4, kmarker4x, 370, 450, 300);
  kmarker4x-=kmarker4dx;
  ctx.drawImage(kmarker5, kmarker5x, 370, 450, 300);
  kmarker5x-=kmarker5dx;
  ctx.drawImage(kmarker6, kmarker6x, 370, 450, 300);
  kmarker6x-=kmarker6dx;
  ctx.drawImage(kmarker7, kmarker7x, 370, 450, 300);
  kmarker7x-=kmarker7dx;
  ctx.drawImage(finflag, finflagx, 430, 350, 200);
  finflagx-=finflagdx;
  ctx.drawImage(img, x, 430);
  x+=dx;
  ctx.drawImage(tree2, tree2x, 220);
  tree2x-=tree2dx;
  ctx.drawImage(tree2, tree4x, 220);
  tree4x-=tree2dx;
  ctx.drawImage(tree2, tree6x, 220);
  tree6x-=tree2dx;
  ctx.drawImage(tree2, tree8x, 220);
  tree8x-=tree2dx;
  ctx.drawImage(tree2, tree10x, 220);
  tree10x-=tree2dx;
  ctx.drawImage(tree2, tree12x, 220);
  tree12x-=tree2dx;
  ctx.drawImage(tree2, tree14x, 220);
  tree14x-=tree2dx;
  if(x>score){
    cancelAnimationFrame(cartoon);
  }
}

function sendToDb(img){
  console.log("I'm here!");
  document.getElementById("gametag").value=gametag;
  document.getElementById("fname").value=playername;
  document.getElementById("score").value=score;
}

function scrollDown(){
  window.scrollTo(0, 1000);
}